spring.config.import=optional:file:.env[.properties]
spring.application.name=${SPRING_APPLICATION_NAME}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

jwt.expiration=${JWT_EXPIRATION}
jwt.secret=${JWT_SECRET}

telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.chat.id=${TELEGRAM_CHAT_ID}
telegram.api.url=${TELEGRAM_API_URL}

rental.overdue.check.cron=${RENTAL_OVERDUE_CHECK_CRON}
rental.overdue.check.zone=${RENTAL_OVERDUE_CHECK_ZONE}
