spring.config.import=optional:file:.env[.properties]
spring.application.name=${SPRING_APPLICATION_NAME}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
